"""K-file Exporter for Keyword Manager

Card 정의를 활용한 정확한 K-file 포맷 출력을 담당합니다.
"""
from typing import Dict, List, Any, Optional, TYPE_CHECKING
from dataclasses import dataclass

if TYPE_CHECKING:
    from gui.app_context import ParsedModelData


@dataclass
class ExportOptions:
    """Export 옵션"""
    # 필드 너비 (기본값: 10)
    default_field_width: int = 10
    # 노드 좌표 너비 (기본값: 16)
    node_coord_width: int = 16
    # Float 출력 형식: 'fixed', 'scientific', 'auto'
    float_format: str = 'auto'
    # Float 소수점 자릿수
    float_precision: int = 6
    # 주석 포함 여부
    include_comments: bool = True
    # 수정된 항목만 Export
    modified_only: bool = False
    # 빈 카테고리 건너뛰기
    skip_empty: bool = True


class KFileExporter:
    """K-file 내보내기 클래스

    Card 정의를 활용하여 정확한 LS-DYNA K-file 형식으로 출력합니다.
    각 키워드의 필드 정의에 따라 적절한 포맷을 적용합니다.
    """

    def __init__(self, model: 'ParsedModelData', options: Optional[ExportOptions] = None):
        self._model = model
        self._options = options or ExportOptions()

    @property
    def options(self) -> ExportOptions:
        return self._options

    @options.setter
    def options(self, value: ExportOptions):
        self._options = value

    def export(self, filepath: str) -> bool:
        """K-file로 내보내기

        Args:
            filepath: 저장할 파일 경로

        Returns:
            성공 여부
        """
        try:
            lines = self.generate_content()
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines))
            return True
        except Exception as e:
            print(f"[KFileExporter] Export error: {e}")
            return False

    def generate_content(self) -> List[str]:
        """전체 K-file 내용 생성"""
        lines = []

        # 헤더
        if self._options.include_comments:
            lines.append("$# LS-DYNA Keyword file exported by LaminateModeller")
            lines.append("$# Generated by Keyword Manager - KFileExporter")
            lines.append("$")

        lines.append("*KEYWORD")

        # 타이틀
        lines.append("*TITLE")
        lines.append(f"{self._model.filename if self._model else 'Untitled'}")

        if self._options.include_comments:
            lines.append("$")

        # 각 섹션 출력
        self._export_nodes(lines)
        self._export_elements(lines)
        self._export_parts(lines)
        self._export_sections(lines)
        self._export_materials(lines)
        self._export_contacts(lines)
        self._export_sets(lines)
        self._export_controls(lines)
        self._export_databases(lines)
        self._export_boundaries(lines)
        self._export_loads(lines)
        self._export_initials(lines)
        self._export_constraineds(lines)

        # 종료
        if self._options.include_comments:
            lines.append("$")
        lines.append("*END")

        return lines

    def _format_int(self, value: Any, width: int = 10) -> str:
        """정수 포맷"""
        try:
            return f"{int(value):>{width}d}"
        except (ValueError, TypeError):
            return f"{0:>{width}d}"

    def _format_float(self, value: Any, width: int = 10, precision: int = None) -> str:
        """실수 포맷"""
        if precision is None:
            precision = self._options.float_precision

        try:
            fval = float(value)
        except (ValueError, TypeError):
            fval = 0.0

        # Auto format 선택
        if self._options.float_format == 'scientific':
            return f"{fval:>{width}.{precision}e}"
        elif self._options.float_format == 'fixed':
            return f"{fval:>{width}.{precision}f}"
        else:  # auto
            # 값에 따라 적절한 형식 선택
            if fval == 0.0:
                return f"{0.0:>{width}.1f}"
            elif abs(fval) >= 1e6 or abs(fval) < 1e-4:
                # Scientific notation for very large or small values
                exp_precision = max(1, precision - 4)  # 지수 표기 시 정밀도 조정
                return f"{fval:>{width}.{exp_precision}e}"
            else:
                return f"{fval:>{width}.{precision}g}"

    def _format_str(self, value: Any, width: int = 10) -> str:
        """문자열 포맷 (좌측 정렬)"""
        s = str(value) if value else ""
        return f"{s:<{width}}"

    def _add_section_comment(self, lines: List[str], section_name: str):
        """섹션 주석 추가"""
        if self._options.include_comments:
            lines.append("$")
            lines.append(f"$# {section_name}")

    def _export_nodes(self, lines: List[str]):
        """노드 출력"""
        if not self._model.nodes:
            return

        self._add_section_comment(lines, "NODES")
        lines.append("*NODE")

        w = self._options.default_field_width  # 8 or 10
        cw = self._options.node_coord_width    # 16

        for node in self._model.nodes:
            nid = getattr(node, 'nid', 0)
            x = getattr(node, 'x', 0.0)
            y = getattr(node, 'y', 0.0)
            z = getattr(node, 'z', 0.0)
            tc = getattr(node, 'tc', 0)
            rc = getattr(node, 'rc', 0)

            # NID, X, Y, Z, TC, RC
            line = self._format_int(nid, 8)
            line += self._format_float(x, cw, 8)
            line += self._format_float(y, cw, 8)
            line += self._format_float(z, cw, 8)
            line += self._format_int(tc, 8)
            line += self._format_int(rc, 8)

            lines.append(line)

    def _export_elements(self, lines: List[str]):
        """요소 출력"""
        # Shell elements
        if self._model.shells:
            self._add_section_comment(lines, "SHELL ELEMENTS")
            lines.append("*ELEMENT_SHELL")

            for elem in self._model.shells:
                eid = getattr(elem, 'eid', 0)
                pid = getattr(elem, 'pid', 0)
                nodes = getattr(elem, 'nodes', [])

                # Pad nodes to 4
                nodes_padded = list(nodes) + [0] * (4 - len(nodes))

                line = self._format_int(eid, 8)
                line += self._format_int(pid, 8)
                for n in nodes_padded[:4]:
                    line += self._format_int(n, 8)

                lines.append(line)

        # Solid elements
        if self._model.solids:
            self._add_section_comment(lines, "SOLID ELEMENTS")
            lines.append("*ELEMENT_SOLID")

            for elem in self._model.solids:
                eid = getattr(elem, 'eid', 0)
                pid = getattr(elem, 'pid', 0)
                nodes = getattr(elem, 'nodes', [])

                # Pad nodes to 8
                nodes_padded = list(nodes) + [0] * (8 - len(nodes))

                line = self._format_int(eid, 8)
                line += self._format_int(pid, 8)
                for n in nodes_padded[:8]:
                    line += self._format_int(n, 8)

                lines.append(line)

        # Beam elements
        if self._model.beams:
            self._add_section_comment(lines, "BEAM ELEMENTS")
            lines.append("*ELEMENT_BEAM")

            for elem in self._model.beams:
                eid = getattr(elem, 'eid', 0)
                pid = getattr(elem, 'pid', 0)
                nodes = getattr(elem, 'nodes', [])

                n1 = nodes[0] if len(nodes) > 0 else 0
                n2 = nodes[1] if len(nodes) > 1 else 0
                n3 = nodes[2] if len(nodes) > 2 else 0

                line = self._format_int(eid, 8)
                line += self._format_int(pid, 8)
                line += self._format_int(n1, 8)
                line += self._format_int(n2, 8)
                line += self._format_int(n3, 8)

                lines.append(line)

    def _export_parts(self, lines: List[str]):
        """파트 출력"""
        if not self._model.parts:
            return

        self._add_section_comment(lines, "PARTS")

        for part in self._model.parts:
            lines.append("*PART")

            # Title line
            name = getattr(part, 'name', '')
            lines.append(name if name else "Untitled Part")

            # Card 1: PID, SECID, MID, EOSID, HGID, GRAV, ADPOPT, TMID
            pid = getattr(part, 'pid', 0)
            secid = getattr(part, 'secid', 0)
            mid = getattr(part, 'mid', 0)
            eosid = getattr(part, 'eosid', 0)
            hgid = getattr(part, 'hgid', 0)
            grav = getattr(part, 'grav', 0)
            adpopt = getattr(part, 'adpopt', 0)
            tmid = getattr(part, 'tmid', 0)

            line = self._format_int(pid, 10)
            line += self._format_int(secid, 10)
            line += self._format_int(mid, 10)
            line += self._format_int(eosid, 10)
            line += self._format_int(hgid, 10)
            line += self._format_int(grav, 10)
            line += self._format_int(adpopt, 10)
            line += self._format_int(tmid, 10)

            lines.append(line)

    def _export_sections(self, lines: List[str]):
        """섹션 출력"""
        if not self._model.sections:
            return

        self._add_section_comment(lines, "SECTIONS")

        for section in self._model.sections:
            keyword_type = getattr(section, 'keyword_type', 'SECTION_SHELL')
            lines.append(f"*{keyword_type}")

            # Title if present
            title = getattr(section, 'title', '')
            if title:
                lines.append(f"$# {title}")

            secid = getattr(section, 'secid', 0)
            elform = getattr(section, 'elform', 2)
            shrf = getattr(section, 'shrf', 1.0)
            nip = getattr(section, 'nip', 2)
            propt = getattr(section, 'propt', 0.0)
            qr_irid = getattr(section, 'qr_irid', 0)
            icomp = getattr(section, 'icomp', 0)
            setyp = getattr(section, 'setyp', 1)

            # Card 1
            line = self._format_int(secid, 10)
            line += self._format_int(elform, 10)
            line += self._format_float(shrf, 10)
            line += self._format_int(nip, 10)
            line += self._format_float(propt, 10)
            line += self._format_int(qr_irid, 10)
            line += self._format_int(icomp, 10)
            line += self._format_int(setyp, 10)

            lines.append(line)

            # Card 2 - Thickness values for SECTION_SHELL
            if 'SHELL' in keyword_type.upper():
                t1 = getattr(section, 't1', 0.0)
                t2 = getattr(section, 't2', 0.0)
                t3 = getattr(section, 't3', 0.0)
                t4 = getattr(section, 't4', 0.0)
                nloc = getattr(section, 'nloc', 0.0)

                line2 = self._format_float(t1, 10)
                line2 += self._format_float(t2, 10)
                line2 += self._format_float(t3, 10)
                line2 += self._format_float(t4, 10)
                line2 += self._format_float(nloc, 10)

                lines.append(line2)

    def _export_materials(self, lines: List[str]):
        """재료 출력"""
        if not self._model.materials:
            return

        self._add_section_comment(lines, "MATERIALS")

        for material in self._model.materials:
            keyword_type = getattr(material, 'keyword_type', 'MAT_ELASTIC')
            lines.append(f"*{keyword_type}")

            # Title if present
            title = getattr(material, 'title', '')
            if title:
                lines.append(f"$# {title}")

            mid = getattr(material, 'mid', 0)
            ro = getattr(material, 'ro', 0.0)
            e = getattr(material, 'e', 0.0)
            pr = getattr(material, 'pr', 0.0)
            da = getattr(material, 'da', 0.0)
            db = getattr(material, 'db', 0.0)
            k = getattr(material, 'k', 0.0)

            # Card 1
            line = self._format_int(mid, 10)
            line += self._format_float(ro, 10)
            line += self._format_float(e, 10)
            line += self._format_float(pr, 10)
            line += self._format_float(da, 10)
            line += self._format_float(db, 10)
            line += self._format_float(k, 10)

            lines.append(line)

    def _export_contacts(self, lines: List[str]):
        """접촉 출력"""
        if not self._model.contacts:
            return

        self._add_section_comment(lines, "CONTACTS")

        for contact in self._model.contacts:
            keyword_type = getattr(contact, 'keyword_type', 'CONTACT_AUTOMATIC_SURFACE_TO_SURFACE')
            lines.append(f"*{keyword_type}")

            # Card 1: SSID, MSID, SSTYP, MSTYP, SBOXID, MBOXID, SPR, MPR
            ssid = getattr(contact, 'ssid', 0)
            msid = getattr(contact, 'msid', 0)
            sstyp = getattr(contact, 'sstyp', 0)
            mstyp = getattr(contact, 'mstyp', 0)
            sboxid = getattr(contact, 'sboxid', 0)
            mboxid = getattr(contact, 'mboxid', 0)
            spr = getattr(contact, 'spr', 0)
            mpr = getattr(contact, 'mpr', 0)

            line1 = self._format_int(ssid, 10)
            line1 += self._format_int(msid, 10)
            line1 += self._format_int(sstyp, 10)
            line1 += self._format_int(mstyp, 10)
            line1 += self._format_int(sboxid, 10)
            line1 += self._format_int(mboxid, 10)
            line1 += self._format_int(spr, 10)
            line1 += self._format_int(mpr, 10)

            lines.append(line1)

            # Card 2: FS, FD, DC, VC, VDC, PENCHK, BT, DT
            fs = getattr(contact, 'fs', 0.0)
            fd = getattr(contact, 'fd', 0.0)
            dc = getattr(contact, 'dc', 0.0)
            vc = getattr(contact, 'vc', 0.0)
            vdc = getattr(contact, 'vdc', 0.0)
            penchk = getattr(contact, 'penchk', 0)
            bt = getattr(contact, 'bt', 0.0)
            dt = getattr(contact, 'dt', 1e20)

            line2 = self._format_float(fs, 10)
            line2 += self._format_float(fd, 10)
            line2 += self._format_float(dc, 10)
            line2 += self._format_float(vc, 10)
            line2 += self._format_float(vdc, 10)
            line2 += self._format_int(penchk, 10)
            line2 += self._format_float(bt, 10)
            line2 += self._format_float(dt, 10)

            lines.append(line2)

    def _export_sets(self, lines: List[str]):
        """세트 출력"""
        if not self._model.sets:
            return

        self._add_section_comment(lines, "SETS")

        for set_item in self._model.sets:
            keyword_type = getattr(set_item, 'keyword_type', 'SET_NODE_LIST')
            lines.append(f"*{keyword_type}")

            # Title if present
            title = getattr(set_item, 'title', '')
            if title:
                lines.append(f"$# {title}")

            # Card 1: SID, DA1, DA2, DA3, DA4, SOLVER
            sid = getattr(set_item, 'sid', 0)
            da1 = getattr(set_item, 'da1', 0.0)
            da2 = getattr(set_item, 'da2', 0.0)
            da3 = getattr(set_item, 'da3', 0.0)
            da4 = getattr(set_item, 'da4', 0.0)
            solver = getattr(set_item, 'solver', '')

            line1 = self._format_int(sid, 10)
            line1 += self._format_float(da1, 10)
            line1 += self._format_float(da2, 10)
            line1 += self._format_float(da3, 10)
            line1 += self._format_float(da4, 10)
            line1 += self._format_str(solver, 10)

            lines.append(line1)

            # Members (8 per line)
            members = getattr(set_item, 'members', [])
            if members:
                for i in range(0, len(members), 8):
                    chunk = members[i:i+8]
                    line = ''.join(self._format_int(m, 10) for m in chunk)
                    lines.append(line)

    def _export_controls(self, lines: List[str]):
        """컨트롤 키워드 출력"""
        if not self._model.controls:
            return

        for ctrl_type, items in self._model.controls.items():
            if not items:
                continue

            self._add_section_comment(lines, f"CONTROL_{ctrl_type.upper()}")

            for item in items:
                keyword_type = getattr(item, 'keyword_type', f'CONTROL_{ctrl_type.upper()}')
                lines.append(f"*{keyword_type}")

                # 기본 속성들 출력 (raw_data가 있으면 사용)
                raw_data = getattr(item, 'raw_data', None)
                if raw_data:
                    for raw_line in raw_data:
                        lines.append(raw_line)
                else:
                    # 타입별 처리
                    self._export_control_item(lines, ctrl_type, item)

    def _export_control_item(self, lines: List[str], ctrl_type: str, item: Any):
        """개별 컨트롤 아이템 출력"""
        if ctrl_type == 'termination':
            endtim = getattr(item, 'endtim', 0.0)
            endcyc = getattr(item, 'endcyc', 0)
            dtmin = getattr(item, 'dtmin', 0.0)
            endeng = getattr(item, 'endeng', 0.0)
            endmas = getattr(item, 'endmas', 0.0)

            line = self._format_float(endtim, 10)
            line += self._format_int(endcyc, 10)
            line += self._format_float(dtmin, 10)
            line += self._format_float(endeng, 10)
            line += self._format_float(endmas, 10)
            lines.append(line)

        elif ctrl_type == 'timestep':
            dtinit = getattr(item, 'dtinit', 0.0)
            tssfac = getattr(item, 'tssfac', 0.9)
            isdo = getattr(item, 'isdo', 0)
            tslimt = getattr(item, 'tslimt', 0.0)
            dt2ms = getattr(item, 'dt2ms', 0.0)
            lctm = getattr(item, 'lctm', 0)
            erode = getattr(item, 'erode', 0)
            ms1st = getattr(item, 'ms1st', 0)

            line = self._format_float(dtinit, 10)
            line += self._format_float(tssfac, 10)
            line += self._format_int(isdo, 10)
            line += self._format_float(tslimt, 10)
            line += self._format_float(dt2ms, 10)
            line += self._format_int(lctm, 10)
            line += self._format_int(erode, 10)
            line += self._format_int(ms1st, 10)
            lines.append(line)

        elif ctrl_type == 'energy':
            hgen = getattr(item, 'hgen', 2)
            rwen = getattr(item, 'rwen', 2)
            slnten = getattr(item, 'slnten', 2)
            rylen = getattr(item, 'rylen', 2)

            line = self._format_int(hgen, 10)
            line += self._format_int(rwen, 10)
            line += self._format_int(slnten, 10)
            line += self._format_int(rylen, 10)
            lines.append(line)

        elif ctrl_type == 'hourglass':
            ihq = getattr(item, 'ihq', 1)
            qh = getattr(item, 'qh', 0.1)

            line = self._format_int(ihq, 10)
            line += self._format_float(qh, 10)
            lines.append(line)

    def _export_databases(self, lines: List[str]):
        """데이터베이스 키워드 출력"""
        if not self._model.databases:
            return

        for db_type, items in self._model.databases.items():
            if not items:
                continue

            self._add_section_comment(lines, f"DATABASE_{db_type.upper()}")

            for item in items:
                keyword_type = getattr(item, 'keyword_type', f'DATABASE_{db_type.upper()}')
                lines.append(f"*{keyword_type}")

                # 기본 필드: DT, BINARY, LCUR, IOOPT
                dt = getattr(item, 'dt', 0.0)
                binary = getattr(item, 'binary', 0)
                lcur = getattr(item, 'lcur', 0)
                ioopt = getattr(item, 'ioopt', 0)

                line = self._format_float(dt, 10)
                line += self._format_int(binary, 10)
                line += self._format_int(lcur, 10)
                line += self._format_int(ioopt, 10)
                lines.append(line)

    def _export_boundaries(self, lines: List[str]):
        """경계조건 출력"""
        if not self._model.boundaries:
            return

        for bnd_type, items in self._model.boundaries.items():
            if not items:
                continue

            self._add_section_comment(lines, f"BOUNDARY_{bnd_type.upper()}")

            for item in items:
                keyword_type = getattr(item, 'keyword_type', f'BOUNDARY_{bnd_type.upper()}')
                lines.append(f"*{keyword_type}")

                if bnd_type == 'spc':
                    # BOUNDARY_SPC_SET or BOUNDARY_SPC_NODE
                    nid = getattr(item, 'nid', 0)
                    nsid = getattr(item, 'nsid', 0)
                    cid = getattr(item, 'cid', 0)
                    dofx = getattr(item, 'dofx', 0)
                    dofy = getattr(item, 'dofy', 0)
                    dofz = getattr(item, 'dofz', 0)
                    dofrx = getattr(item, 'dofrx', 0)
                    dofry = getattr(item, 'dofry', 0)
                    dofrz = getattr(item, 'dofrz', 0)

                    if 'SET' in keyword_type.upper():
                        line = self._format_int(nsid, 10)
                    else:
                        line = self._format_int(nid, 10)
                    line += self._format_int(cid, 10)
                    line += self._format_int(dofx, 10)
                    line += self._format_int(dofy, 10)
                    line += self._format_int(dofz, 10)
                    line += self._format_int(dofrx, 10)
                    line += self._format_int(dofry, 10)
                    line += self._format_int(dofrz, 10)
                    lines.append(line)

                elif bnd_type == 'motion':
                    # BOUNDARY_PRESCRIBED_MOTION
                    nid = getattr(item, 'nid', 0)
                    nsid = getattr(item, 'nsid', 0)
                    dof = getattr(item, 'dof', 0)
                    vad = getattr(item, 'vad', 0)
                    lcid = getattr(item, 'lcid', 0)
                    sf = getattr(item, 'sf', 1.0)
                    vid = getattr(item, 'vid', 0)
                    death = getattr(item, 'death', 1e28)
                    birth = getattr(item, 'birth', 0.0)

                    if 'SET' in keyword_type.upper():
                        line = self._format_int(nsid, 10)
                    else:
                        line = self._format_int(nid, 10)
                    line += self._format_int(dof, 10)
                    line += self._format_int(vad, 10)
                    line += self._format_int(lcid, 10)
                    line += self._format_float(sf, 10)
                    line += self._format_int(vid, 10)
                    line += self._format_float(death, 10)
                    line += self._format_float(birth, 10)
                    lines.append(line)

    def _export_loads(self, lines: List[str]):
        """하중 출력"""
        if not self._model.loads:
            return

        for load_type, items in self._model.loads.items():
            if not items:
                continue

            self._add_section_comment(lines, f"LOAD_{load_type.upper()}")

            for item in items:
                keyword_type = getattr(item, 'keyword_type', f'LOAD_{load_type.upper()}')
                lines.append(f"*{keyword_type}")

                if load_type == 'node':
                    nid = getattr(item, 'nid', 0)
                    dof = getattr(item, 'dof', 0)
                    lcid = getattr(item, 'lcid', 0)
                    sf = getattr(item, 'sf', 1.0)
                    cid = getattr(item, 'cid', 0)

                    line = self._format_int(nid, 10)
                    line += self._format_int(dof, 10)
                    line += self._format_int(lcid, 10)
                    line += self._format_float(sf, 10)
                    line += self._format_int(cid, 10)
                    lines.append(line)

                elif load_type == 'body':
                    lcid = getattr(item, 'lcid', 0)
                    sf = getattr(item, 'sf', 1.0)
                    lciddr = getattr(item, 'lciddr', 0)
                    xc = getattr(item, 'xc', 0.0)
                    yc = getattr(item, 'yc', 0.0)
                    zc = getattr(item, 'zc', 0.0)

                    line = self._format_int(lcid, 10)
                    line += self._format_float(sf, 10)
                    line += self._format_int(lciddr, 10)
                    line += self._format_float(xc, 10)
                    line += self._format_float(yc, 10)
                    line += self._format_float(zc, 10)
                    lines.append(line)

    def _export_initials(self, lines: List[str]):
        """초기조건 출력"""
        if not self._model.initials:
            return

        for init_type, items in self._model.initials.items():
            if not items:
                continue

            self._add_section_comment(lines, f"INITIAL_{init_type.upper()}")

            for item in items:
                keyword_type = getattr(item, 'keyword_type', f'INITIAL_{init_type.upper()}')
                lines.append(f"*{keyword_type}")

                if init_type == 'velocity':
                    nsid = getattr(item, 'nsid', 0)
                    nsidex = getattr(item, 'nsidex', 0)
                    boxid = getattr(item, 'boxid', 0)
                    irigid = getattr(item, 'irigid', 0)

                    line1 = self._format_int(nsid, 10)
                    line1 += self._format_int(nsidex, 10)
                    line1 += self._format_int(boxid, 10)
                    line1 += self._format_int(irigid, 10)
                    lines.append(line1)

                    vx = getattr(item, 'vx', 0.0)
                    vy = getattr(item, 'vy', 0.0)
                    vz = getattr(item, 'vz', 0.0)
                    vxr = getattr(item, 'vxr', 0.0)
                    vyr = getattr(item, 'vyr', 0.0)
                    vzr = getattr(item, 'vzr', 0.0)

                    line2 = self._format_float(vx, 10)
                    line2 += self._format_float(vy, 10)
                    line2 += self._format_float(vz, 10)
                    line2 += self._format_float(vxr, 10)
                    line2 += self._format_float(vyr, 10)
                    line2 += self._format_float(vzr, 10)
                    lines.append(line2)

    def _export_constraineds(self, lines: List[str]):
        """구속조건 출력"""
        if not self._model.constraineds:
            return

        for const_type, items in self._model.constraineds.items():
            if not items:
                continue

            self._add_section_comment(lines, f"CONSTRAINED_{const_type.upper()}")

            for item in items:
                keyword_type = getattr(item, 'keyword_type', f'CONSTRAINED_{const_type.upper()}')
                lines.append(f"*{keyword_type}")

                if const_type == 'rigid_body':
                    pid = getattr(item, 'pid', 0)
                    cid = getattr(item, 'cid', 0)
                    nsid = getattr(item, 'nsid', 0)
                    pnode = getattr(item, 'pnode', 0)
                    iprt = getattr(item, 'iprt', 0)
                    drflag = getattr(item, 'drflag', 0)
                    rrflag = getattr(item, 'rrflag', 0)

                    line = self._format_int(pid, 10)
                    line += self._format_int(cid, 10)
                    line += self._format_int(nsid, 10)
                    line += self._format_int(pnode, 10)
                    line += self._format_int(iprt, 10)
                    line += self._format_int(drflag, 10)
                    line += self._format_int(rrflag, 10)
                    lines.append(line)

                elif const_type == 'joint':
                    # 기본 joint 카드
                    jid = getattr(item, 'jid', 0)
                    pida = getattr(item, 'pida', 0)
                    pidb = getattr(item, 'pidb', 0)

                    line = self._format_int(jid, 10)
                    line += self._format_int(pida, 10)
                    line += self._format_int(pidb, 10)
                    lines.append(line)

                elif const_type == 'spotweld':
                    n1 = getattr(item, 'n1', 0)
                    n2 = getattr(item, 'n2', 0)
                    sn = getattr(item, 'sn', 0.0)
                    ss = getattr(item, 'ss', 0.0)

                    line = self._format_int(n1, 10)
                    line += self._format_int(n2, 10)
                    line += self._format_float(sn, 10)
                    line += self._format_float(ss, 10)
                    lines.append(line)
